version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8082:8082"
    # Эти свойства перегружают соответствующие в application.yml
    environment:
     - SPRING_DATA_MONGO_DB = tests
     - SPRING_DATA_USERNAME = Employeeadmin
     - SPRING_DATA_PASSWORD = password
    networks:
      - nw
networks:
  nw:
