spring:
  datasource:
  url: jdbc:h2:mem:testdb
  initialization-mode: never

  jpa:
  generate-ddl: false
  hibernate:
  ddl-auto: none

  show-sql: true

  logging:
  level:
  ROOT: ERROR

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml