spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: ALWAYS

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

    generate-ddl: true

    hibernate:
      ddl-auto: update

    show-sql: true

logging:
  level:
    ROOT: ERROR