#spring:
#  data:
#    mongodb:
#      database: library
#server:
#  port: 8082
#  host: 8082
spring:
  data:
    mongodb:
    username: Employeeadmin
    password: password
    database: test
    port: 5435
    host: 5435

#    uri: mongodb://Employeeadmin:password@5435:5435/test

  mongock:
    runner-type: "ApplicationRunner" # default
    #runner-type: "InitializingBean"
    change-logs-scan-package:
      - ru.otus.spring.mongock.changelog

