spring:
  data:
      username: Employeeadmin
      password: password
      database: tests

  mongock:
    runner-type: "ApplicationRunner" # default
    #runner-type: "InitializingBean"
    change-logs-scan-package:
      - ru.otus.spring.mongock.changelog

